[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
language = "system"
entry = "cargo fmt --all"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
language = "system"
entry = "cargo clippy --all-targets -- -D warnings"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "oxfmt"
name = "oxfmt"
language = "system"
entry = "pnpm oxfmt"
types = [
  "ts",
  "json",
  "yaml",
  "markdown",
  "vue",
  "svelte",
  "astro",
  "html",
  "css",
  "scss"
]
pass_filenames = true

[[repos.hooks]]
id = "oxlint"
name = "oxlint"
language = "system"
entry = "pnpm oxlint --type-aware --type-check"
types = ["ts"]
pass_filenames = true

[[repos.hooks]]
id = "tombi"
name = "tombi format"
language = "system"
entry = "tombi format"
types = ["toml"]
pass_filenames = true

[[repos.hooks]]
id = "actionlint"
name = "actionlint"
language = "system"
entry = "actionlint"
files = "^.github/workflows/.*\\.ya?ml$"
pass_filenames = false
