import css from "@webref/css";
import { buildKeywordToTypes, extractTerminalTypes } from "./keyword-kinds.ts";
import { buildFunctionToKinds } from "./function-kinds.ts";

// lightningcss SyntaxComponentKind variants that share a bit with keyword kinds.
// Names must match the keyword-kinds naming convention so that overlapping
// kinds (e.g. "color") naturally deduplicate.
const SYNTAX_COMPONENT_KINDS: { kind: string; variant: string }[] = [
  { kind: "length", variant: "Length" },
  { kind: "number", variant: "Number" },
  { kind: "percentage", variant: "Percentage" },
  { kind: "color", variant: "Color" },
  { kind: "image", variant: "Image" },
  { kind: "url", variant: "Url" },
  { kind: "integer", variant: "Integer" },
  { kind: "angle", variant: "Angle" },
  { kind: "time", variant: "Time" },
  { kind: "resolution", variant: "Resolution" },
  { kind: "transform-function", variant: "TransformFunction" },
  { kind: "transform-list", variant: "TransformList" },
  { kind: "string", variant: "String" },
  { kind: "custom-ident", variant: "CustomIdent" },
];

function kindToConstName(kind: string): string {
  return kind.replaceAll("-", "_").replaceAll("+", "_plus_").toUpperCase();
}

function collectAllKinds(
  keywordMap: Record<string, string[]>,
  functionMap: Record<string, string[]>,
): string[] {
  const kinds = new Set<string>();

  for (const values of Object.values(keywordMap)) {
    for (const kind of values) kinds.add(kind);
  }
  for (const values of Object.values(functionMap)) {
    for (const kind of values) kinds.add(kind);
  }
  for (const { kind } of SYNTAX_COMPONENT_KINDS) {
    kinds.add(kind);
  }

  return [...kinds].sort();
}

function generateBitflags(allKinds: string[]): string {
  const lines: string[] = [];
  lines.push("bitflags::bitflags! {");
  lines.push("    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");
  lines.push("    pub struct KindSet: u128 {");

  for (let i = 0; i < allKinds.length; i++) {
    lines.push(`        const ${kindToConstName(allKinds[i])} = 1 << ${i};`);
  }

  lines.push("");
  lines.push(
    "        // Composite alias: LengthPercentage = Length | Percentage",
  );
  lines.push(
    "        const LENGTH_PERCENTAGE = KindSet::LENGTH.bits() | KindSet::PERCENTAGE.bits();",
  );

  lines.push("    }");
  lines.push("}");
  return lines.join("\n");
}

function generateLookupFn(
  fnName: string,
  map: Record<string, string[]>,
): string {
  const lines: string[] = [];
  lines.push(`pub fn ${fnName}(name: &str) -> Option<KindSet> {`);
  lines.push("    match name {");

  for (const [name, kinds] of Object.entries(map)) {
    const consts = kinds.map((k) => `KindSet::${kindToConstName(k)}`);
    const combined = consts.join(" | ");
    const escaped = name.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
    lines.push(`        "${escaped}" => Some(${combined}),`);
  }

  lines.push("        _ => None,");
  lines.push("    }");
  lines.push("}");
  return lines.join("\n");
}

async function main() {
  const outPath = Deno.args[0];
  if (!outPath) {
    console.error("Usage: deno run main.ts <output-path>");
    Deno.exit(1);
  }

  const data = await css.listAll();
  const terminalTypes = extractTerminalTypes(data.types ?? []);
  const keywordMap = buildKeywordToTypes(terminalTypes);
  const functionMap = buildFunctionToKinds(data.functions ?? []);
  const allKinds = collectAllKinds(keywordMap, functionMap);

  if (allKinds.length > 128) {
    console.error(
      `Error: too many kinds (${allKinds.length}) for u128 bitflags`,
    );
    Deno.exit(1);
  }

  const sections = [
    "// Generated by scripts/gen-kind-set/main.ts",
    "// Do not edit manually.",
    "",
    generateBitflags(allKinds),
    "",
    generateLookupFn("lookup_keyword_kinds", keywordMap),
    "",
    generateLookupFn("lookup_function_kinds", functionMap),
    "",
  ];

  const code = sections.join("\n");
  await Deno.writeTextFile(outPath, code);
  console.log(
    `Written KindSet (${allKinds.length} kinds) + lookup functions to ${outPath}`,
  );
}

if (import.meta.main) {
  await main();
}
