import type { KindData } from "./kind-data.ts";

export function generateValueKindSchema({ allKinds }: Pick<KindData, "allKinds">): string {
  // length-percentage is a composite alias (Length | Percentage) not present in allKinds
  const kinds = [...allKinds, "length-percentage"].sort((a, b) => a.localeCompare(b));

  const schema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "CSS Variable Kit - Value Kind",
    description:
      "A CSS value kind. Valid values for `types` and `allowedKinds` in the enforce-variable-use rule config.",
    type: "string",
    enum: kinds,
  };
  return JSON.stringify(schema, null, 2) + "\n";
}

function invertMap(map: Record<string, string[]>): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  for (const [key, kinds] of Object.entries(map)) {
    for (const kind of kinds) {
      (result[kind] ??= []).push(key);
    }
  }
  return result;
}

export function generateKindDoc({
  allKinds,
  keywordMap,
  functionMap,
  dimensionUnitMap,
}: KindData): string {
  const keywordsByKind = invertMap(keywordMap);
  const functionsByKind = invertMap(functionMap);
  const unitsByKind = invertMap(dimensionUnitMap);

  const lines: string[] = [
    "<!-- Generated by scripts/gen-value-kind-set/gen-kind-doc.ts -->",
    "<!-- Do not edit manually. -->",
    "",
    "# Value Kinds",
    "",
    "Valid values for `types`, `allowedKinds` in the `enforce-variable-use` rule config.",
    "",
    "In the Example values column, `<...>` denotes a CSS unit (e.g. `<px>` means values like `16px`).",
    "",
    "## Common kinds",
    "",
    "| Kind | Example values | Example properties |",
    "| ---- | -------------- | ------------------ |",
  ];

  const prioritized = [
    "color",
    "length",
    "length-percentage",
    "percentage",
    "number",
    "integer",
    "angle",
    "time",
    "resolution",
    "string",
    "url",
    "image",
    "display",
    "position",
    "line-style",
    "easing-function",
    "filter",
    "transform-function",
    "font-weight-absolute",
    "generic-family",
    "flex",
    "frequency",
  ];
  const prioritizedSet = new Set(prioritized);
  const rest = [...allKinds, "length-percentage"].filter((k) => !prioritizedSet.has(k));
  const orderedKinds = [...prioritized, ...rest];
  const restLines: string[] = [];

  for (const kind of orderedKinds) {
    const keywords = keywordsByKind[kind]?.sort() ?? [];
    const functions = functionsByKind[kind]?.sort() ?? [];
    const units = unitsByKind[kind]?.sort() ?? [];

    // Prefer units and short lowercase keywords as representative examples.
    // Deprioritize generic keywords that appear across many kinds.
    // Workaround: exclude keywords containing ")" — the spec data includes
    // malformed entries like "unsafe-url)" (referrer-policy-modifier).
    const generic = new Set(["auto", "none", "normal", "inherit", "initial", "unset"]);
    const shortKeywords = keywords
      .filter((k) => k === k.toLowerCase() && /^[a-z]/.test(k) && !k.includes(")"))
      .sort(
        (a, b) =>
          (generic.has(a) ? 1 : 0) - (generic.has(b) ? 1 : 0) ||
          a.length - b.length ||
          a.localeCompare(b),
      );
    const sortedFunctions = functions.sort(
      (a, b) =>
        (a.startsWith("-") ? 1 : 0) - (b.startsWith("-") ? 1 : 0) ||
        a.length - b.length ||
        a.localeCompare(b),
    );
    const examples: string[] = [
      ...units.slice(0, 3).map((u) => `<${u}>`),
      ...shortKeywords.slice(0, 3),
      ...sortedFunctions.slice(0, 2).map((f) => `${f}()`),
    ].slice(0, 4);

    if (examples.length === 0 && !prioritizedSet.has(kind)) continue;

    const MANUAL_EXAMPLES: Record<string, string[]> = {
      percentage: ["50%"],
      "length-percentage": ["50%", "<px>", "<em>"],
      number: ["0", "1.5", "progress()"],
      integer: ["0", "1", "sibling-count()"],
    };
    const manualExamples = MANUAL_EXAMPLES[kind];
    if (manualExamples) {
      examples.splice(0, examples.length, ...manualExamples);
    }

    const EXAMPLE_PROPERTIES: Record<string, string[]> = {
      color: ["color", "background-color", "border-color"],
      length: ["width", "margin", "padding", "font-size"],
      "length-percentage": ["width", "margin", "padding"],
      percentage: ["opacity", "width"],
      number: ["opacity", "flex-grow", "line-height"],
      integer: ["z-index", "order", "column-count"],
      angle: ["transform", "rotate"],
      time: ["transition-duration", "animation-duration"],
      resolution: ["resolution"],
      string: ["content"],
      url: ["background-image"],
      image: ["background-image", "list-style-image"],
      display: ["display"],
      position: ["background-position", "object-position"],
      "line-style": ["border-style", "outline-style"],
      "easing-function": ["transition-timing-function", "animation-timing-function"],
      filter: ["filter", "backdrop-filter"],
      "transform-function": ["transform"],
      "font-weight-absolute": ["font-weight"],
      "generic-family": ["font-family"],
      flex: ["grid-template-columns"],
      frequency: ["voice-pitch"],
    };
    const props = EXAMPLE_PROPERTIES[kind];
    const propsFormatted = props ? props.map((p) => `\`${p}\``).join(", ") : "";

    const formatted = examples.map((s) => `\`${s}\``).join(", ");
    if (prioritizedSet.has(kind)) {
      lines.push(`| \`${kind}\` | ${formatted} | ${propsFormatted} |`);
    } else {
      restLines.push(`| \`${kind}\` | ${formatted} |`);
    }
  }

  lines.push("");
  lines.push("## Misc");
  lines.push("");
  lines.push("| Kind | Example values |");
  lines.push("| ---- | -------------- |");
  lines.push(...restLines);
  lines.push("");
  return lines.join("\n");
}
